CAFDataProcessing/elastic-mapping-updater

- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
https://portal.digitalsafe.net/browse/SCMOD-8551
http://sou-jenkins2.swinfra.net/job/CAFDataProcessing/job/CAFDataProcessing~elastic-mapping-updater~support-https~CI/
> Use the protocol specified on the command line

- pom.xml
https://portal.digitalsafe.net/browse/SCMOD-8829
> SCMOD-8829: Centralize dependency management

- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
Jira: https://portal.digitalsafe.net/browse/SCMOD-9690
Dev builds: http://sou-jenkins2.swinfra.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~elastic-mapping-updater~SCMOD-9690~CI/
> SCMOD-9690: Retry test index creation

- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticRequestHandler.java
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- elastic-mapping-updater/src/test/resources/template7.json
Jira: https://portal.digitalsafe.net/browse/SCMOD-9892
> SCMOD-9892: Handle 404 error when getting indexes

- README.md
- elastic-mapping-updater-cli/src/main/java/com/github/cafdataprocessing/elastic/tools/cli/Program.java
- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticSettings.java
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- release-notes-2.0.0.md
Jira: https://portal.digitalsafe.net/browse/SCMOD-10383
> SCMOD-10383: Adding es creds options

- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- elastic-mapping-updater/src/test/resources/template10.json
- elastic-mapping-updater/src/test/resources/template11.json
- elastic-mapping-updater/src/test/resources/template8.json
Jira: https://portal.digitalsafe.net/browse/SCMOD-10180
> SCMOD 10180: Update to ignore sub field issues

- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- elastic-mapping-updater/src/test/resources/template12.json
- elastic-mapping-updater/src/test/resources/template13.json
https://portal.digitalsafe.net/browse/SCMOD-12238
Refer: List of removable mapping params computed from the tips here -https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html#CO82-2
> SCMOD-12238: Prevent attempts to remove unmodifiable properties

- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
Jira: https://portal.digitalsafe.net/browse/SCMOD-13141
> SCMOD-13141: Update allowed mapping parameter changes

- release-notes-2.1.0.md
https://portal.digitalsafe.net/browse/SCMOD-13613
@dermot-hardy Here, [SCMOD-13613](https://portal.digitalsafe.net/browse/SCMOD-13613) starts as a bug, but the fix added does more than just fixing it as I understand as it now allows the addition of unsupported parameters.
But, we can also consider that it's mainly a bug fixed
> SCMOD-13613: Updated release-notes

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater-cli/pom.xml
- elastic-mapping-updater/pom.xml
- pom.xml
- release-notes-2.1.1.md
- release-notes-2.2.0.md
https://portal.digitalsafe.net/browse/SCMOD-15728
> SCMOD-15728: Update release notes

- pom.xml
https://internal.almoctane.com/ui/?p=131002%2F6001&idpId=https%3A%2F%2Fauthenticate.microfocus.net%2Fnidp%2Fsaml2%2Fmetadata#/team-backlog/stories
> US397426: Migrating logging version

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater-cli-image/src/main/docker/assembly.xml
- elastic-mapping-updater-cli/elastic-mapping-updater.bat
- elastic-mapping-updater-cli/pom.xml
- elastic-mapping-updater-cli/src/main/java/com/github/cafdataprocessing/elastic/tools/cli/Program.java
- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdaterConfiguration.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticRequestHandler.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticSettings.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetIndexException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetTemplatesException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/UnexpectedResponseException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/utils/FlatMapUtil.java
- elastic-mapping-updater/src/main/resources/includedLogback.xml
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=437250
> 437250: Update copyright year

- pom.xml
- release-notes-2.3.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=572083
> US572083: Update snakeyaml version to 1.32

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=580238
> US580238: Updating commons-text version

- elastic-mapping-updater-cli-image/pom.xml
- release-notes-2.4.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=593021
> US593021: Updated to run on Java 17

- release-notes-2.4.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=614076
> US614076: Update release notes

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater-cli-image/src/main/docker/assembly.xml
- elastic-mapping-updater-cli-package/pom.xml
- elastic-mapping-updater-cli-package/src/main/assembly/elastic-mapping-updater.xml
- elastic-mapping-updater-cli/elastic-mapping-updater.bat
- elastic-mapping-updater-cli/pom.xml
- elastic-mapping-updater-cli/src/main/java/com/github/cafdataprocessing/elastic/tools/cli/Program.java
- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdaterConfiguration.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticRequestHandler.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticSettings.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetIndexException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetTemplatesException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/UnexpectedResponseException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/utils/FlatMapUtil.java
- elastic-mapping-updater/src/main/resources/includedLogback.xml
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=618048
> US618048: updating headers

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=754139
> US754139: Update guava to 32.1.2

- release-notes-2.4.2.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=769057
> US769057: Update release notes

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater-cli-image/src/main/docker/assembly.xml
- elastic-mapping-updater-cli-package/pom.xml
- elastic-mapping-updater-cli-package/src/main/assembly/elastic-mapping-updater.xml
- elastic-mapping-updater-cli/elastic-mapping-updater.bat
- elastic-mapping-updater-cli/pom.xml
- elastic-mapping-updater-cli/src/main/java/com/github/cafdataprocessing/elastic/tools/cli/Program.java
- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdaterConfiguration.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticRequestHandler.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticSettings.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetIndexException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetTemplatesException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/UnexpectedResponseException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/utils/FlatMapUtil.java
- elastic-mapping-updater/src/main/resources/includedLogback.xml
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108
> US868108: Update Copyright statements to 2024

- release-notes-3.0.1.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=901085
> US901085: Update release-notes-3.0.1.md

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater/pom.xml
- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=888096
> US888096: Use docker image version management plugin

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=919254
> US919254: Update to opensearch-java 2.10.4

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
> US920085: Update to latest base image release

- elastic-mapping-updater-cli-image/pom.xml
- pom.xml
- release-notes-3.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=929026
> US929026: Updated to run on Java 21

- elastic-mapping-updater/pom.xml
- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=946199
> US946199: Use OpenSearch Image in tests

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=956022
> US956022: Update to latest base image release

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=974026
> US974026: Updated to latest base image release

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=977107
> US977107: Updated to latest base image release

- elastic-mapping-updater-cli-image/pom.xml
- elastic-mapping-updater-cli-image/src/main/docker/assembly.xml
- elastic-mapping-updater-cli-package/pom.xml
- elastic-mapping-updater-cli-package/src/main/assembly/elastic-mapping-updater.xml
- elastic-mapping-updater-cli/elastic-mapping-updater.bat
- elastic-mapping-updater-cli/pom.xml
- elastic-mapping-updater-cli/src/main/java/com/github/cafdataprocessing/elastic/tools/cli/Program.java
- elastic-mapping-updater/pom.xml
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdater.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticMappingUpdaterConfiguration.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticProvider.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticRequestHandler.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/ElasticSettings.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetIndexException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/GetTemplatesException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/exceptions/UnexpectedResponseException.java
- elastic-mapping-updater/src/main/java/com/github/cafdataprocessing/elastic/tools/utils/FlatMapUtil.java
- elastic-mapping-updater/src/main/resources/includedLogback.xml
- elastic-mapping-updater/src/test/java/com/github/cafdataprocessing/elastic/tools/test/ElasticMappingUpdaterIT.java
- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1002065
> US1002065: Update copyrights statements to 2025

- release-notes-3.1.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1005321
> US1005321: Release prep

- release-notes-3.1.2.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1034162
> US1034162: Release prep
